### PR TITLE
Fixed External Packages Not Building From The install_dependencies Script

### PR DESCRIPTION
**Pull request by garethellis0**

### CODE REVIEW

**Comment by reoliveira** [comment]
:+1:

**Comment by garethellis0** [comment]
Can you try again with the newest changes?

**Comment by reoliveira** [comment]
will do, though my computer has many issues with the uwsim every time one so see you in like 10 minutes after its done freezing up

**Comment by garethellis0** [comment]
oh rip

**Comment by reoliveira** [comment]
I made sure to close absolutely everything except the single terminal process this time and it had only a small aneurysm this time.

**Comment by reoliveira** [comment]
Looks good, no more duplicated setups

**Pull request merged**
