### PR TITLE
UWSim reformat: Added data folder for our scenes and added script to run simulator in src folder

### LINKED ISSUE #16: Make blender file for gate

### LINKED ISSUE #17: Make blender file for post

### LINKED ISSUE #18: Create simulator environment
Create the environment for the qualifying maneuver and update it with the gate(#16) and post(#17).

### LINKED ISSUE #19: Retrieve simulator camera info
Figure out how to get the information from the cameras in the simulator into our ROS code so we can process it

### LINKED ISSUE #25: Create An Environment of Dice Models
Create some models of the dice we will encounter (note: these dice have the same number on every side) and add them to a UWSim environment

### PR DESCRIPTION
**Pull request by newtoncn**
resolves #16 
resolves #17 
resolves #18 
resolves #19 
resolves #25

### CODE REVIEW

**Comment by garethellis0** [comment]
@newtoncn - just saw your commit, could you post the error you're still getting here?

**Comment by garethellis0** [comment]
Everything's running great on my machine. I was able to run both the `Qualification.xml` and `6-sided-dice.xml` worlds without issue. Good work here :+1: :tada: 

*Bonus Photos*
screenshot from 2018-01-21 07-30-36
screenshot from 2018-01-21 07-30-30

**Comment by reoliveira** [comment]
Please add a section to README.md detailing how to run the simulator. I figured I'd just need to run `install_dependencies.sh` and then found a comment about using `run_simulator.sh <scene>` but that was not sufficient it seems.

**Comment by garethellis0** [comment]
@reoliveira - I think that was all I had to do to get this running, what errors did you encounter?

**Pull request merged**
