### PR TITLE
Cameron/fix rosinstall

### PR DESCRIPTION
**Pull request by newtoncn**
Trying to fix some errors with our install_dependencies that I just noticed. First of all the tensorflow object detector depends on a package vision_msgs which is acquired using rosinstall. This needs to be built before we build our sources.

### CODE REVIEW

**Comment by garethellis0** [comment]
A few things here:
- Looks like the issue with travis not failing was because we were allowing failures in `install_dependencies.sh`. I've opened a PR to change this to exit on failure in #66 (we can probably just branch this PR off that one, so that once CI passes on this one we know it's good)
- Travis doesn't seem to be running on this PR? Might have to close and re-open it, might have to push another commit to trigger it.

**Comment by newtoncn** [comment]
Yeah travis isn't running on your PR either, I was wondering if it was just because I updated using the online editor. I'll look into it tonight when I get home

**Comment by newtoncn** [comment]
I was reading here (https://github.com/travis-ci/travis-ci/issues/7602) that there's some magic 30th commit that causes travis to stall or something (we're on commit 30 D: )

**Comment by newtoncn** [comment]
$ wstool merge https://raw.githubusercontent.com/ubc-subbots/Jormungandr/cameron/fix_rosinstall/.rosinstall
ERROR in config: Forbidden non-SCM element: /opt/ros/kinetic/setup.sh (setup-file)
moveit/moveit:kinetic-ci container finished with errors

**Comment by newtoncn** [comment]
> $ wstool merge https://raw.githubusercontent.com/ubc-subbots/Jormungandr/cameron/fix_rosinstall/.rosinstall
> ERROR in config: Forbidden non-SCM element: /opt/ros/kinetic/setup.sh (setup-file)
> moveit/moveit:kinetic-ci container finished with errors

@garethellis0 You have any idea what this might be? Travis is complaining about the /opt/ros/kinetic/setup.sh but I think this is needed in the .rosinstall file

**Comment by newtoncn** [comment]
It was on the https://github.com/ubc-subbots/Jormungandr/pull/65/commits/a2bc14f2be6eed8b150ca64767af3da01c9c2794 commit

**Comment by newtoncn** [comment]
The issue with the most recent commit is it edits the .rosinstall file after the install_dependencies.sh script is done

**Comment by newtoncn** [comment]
Also it seems to build ok on the travis PR check but not the travis push check

**Comment by garethellis0** [comment]
@newtoncn - not sure what the issue is here? Travis seems happy on both pr and push for this PR? Or do we need the `setup-file` in the `.rosinstall` for some reason?

I believe the `Forbidden non-SCM element` has to do with the fact that over the years, there have been several tools for dependency installation, and the element you added (`setup-file`) is not supported by `wstool` (the most recent tool, and the one we use).

**Comment by newtoncn** [comment]
> @newtoncn - not sure what the issue is here? Travis seems happy on both pr and push for this PR? Or do we need the `setup-file` in the `.rosinstall` for some reason?
> 
> I believe the `Forbidden non-SCM element` has to do with the fact that over the years, there have been several tools for dependency installation, and the element you added (`setup-file`) is not supported by `wstool` (the most recent tool, and the one we use).

The issue is that when the install_dependencies.sh script runs, the .rosinstall file is edited. It adds:
 - setup-file: {local-name: /opt/ros/kinetic/setup.sh}
 to the end of the .rosinstall file, which then causes git to say the file is edited. 

My guess is this line should be in the .rosinstall file, but travis/push doesn't like it for some reason. What is the difference between travis/push and travis/pr?

**Comment by garethellis0** [comment]
> Travis/pr seems to think it's fine. What is the difference between travis/push and travis/pr?

Looks like both travis builds are passing on this PR? Where's this failure?

That said, I have seen this behavior before, I believe it's the same sort of thing I mentioned above, where there are multiple different dependency management tools that ROS has used (and currently uses) that sometimes have conflicting functionality.

**Comment by newtoncn** [comment]
@garethellis0 https://github.com/vcstools/wstool/issues/36 Look like instead of using wstool merge we should just be copying the .rosinstall and calling wstool update?

**Comment by garethellis0** [comment]
This seems like a reasonable solution to me (though a bit hacky).

**Comment by newtoncn** [comment]
Yeah, I think this is the way it has to be, the rosinstall call was failing before, we just weren't catching it in travis. We have to have the setup-file but wstool merge just complains about. Approve?

**Comment by newtoncn** [comment]
@garethellis0 I was checking out the Snowflake repo for the new travis scripts. I may look into implementing that pretty soon here, but can we approve this PR just so that people this weekend have a functioning install script. I think Viral and some others were having problems installing the dependencies of this repo

**Comment by newtoncn** [comment]
I can open up a PR for that shortly if I have time

**Pull request merged**
